# Generated by Django 5.2.1 on 2025-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Достижения")),
                ("desc", models.TextField(verbose_name="Описание достижения")),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на изображение",
                    ),
                ),
                (
                    "condition_json",
                    models.JSONField(default=dict, verbose_name="Условия получения"),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижение",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Локация"
                    ),
                ),
                ("desc", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локация",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователь",
            },
        ),
    ]
