# Generated by Django 5.2.1 on 2025-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_achievements_levels_location_question_word_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="levels",
            name="reward_constraints",
        ),
        migrations.AddConstraint(
            model_name="levels",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("coins_reward", 0), ("type", "TH")),
                        models.Q(("coins_reward__gte", 0), ("type__in", ["TR", "BS"])),
                        _connector="OR",
                    ),
                    ("exp_reward__gte", 0),
                ),
                name="reward_constraints",
            ),
        ),
    ]
