# Generated by Django 5.2.2 on 2025-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_answerimage_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='hp',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное HP'),
        ),
        migrations.AddField(
            model_name='boss',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boss_images/', verbose_name='Изображение'),
        ),
    ]
