# Generated by Django 5.2.2 on 2025-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_boss_hp_boss_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelquestion',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос уровня', 'verbose_name_plural': 'Вопросы уровней'},
        ),
        migrations.AddField(
            model_name='levelquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterUniqueTogether(
            name='levelquestion',
            unique_together={('level', 'question')},
        ),
    ]
