# Generated by Django 5.2.2 on 2025-06-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_levelquestion_options_levelquestion_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translation',
            field=models.TextField(blank=True, null=True, verbose_name='Перевод'),
        ),
    ]
