# Generated by Django 5.2.2 on 2025-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_question_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'ordering': ['location', 'order'], 'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AddField(
            model_name='levels',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
