# Generated by Django 5.2.2 on 2025-06-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_levels_options_levels_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Дополнительный текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_texts', to='education.question')),
            ],
            options={
                'verbose_name': 'Доп. текст вопроса',
                'verbose_name_plural': 'Дополнительные тексты вопросов',
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(verbose_name='Дополнительный перевод')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_translations', to='education.question')),
            ],
            options={
                'verbose_name': 'Доп. перевод',
                'verbose_name_plural': 'Дополнительные переводы',
            },
        ),
    ]
