# Generated by Django 5.2.2 on 2025-06-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_questiontext_questiontranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontranslation',
            name='question',
        ),
        migrations.CreateModel(
            name='QuestionPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('translation', models.TextField(verbose_name='Перевод')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='education.question')),
            ],
            options={
                'verbose_name': 'Фраза вопроса',
                'verbose_name_plural': 'Фразы вопросов',
            },
        ),
        migrations.DeleteModel(
            name='QuestionText',
        ),
        migrations.DeleteModel(
            name='QuestionTranslation',
        ),
    ]
