# Generated by Django 5.2.2 on 2025-06-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_questiontranslation_question_questionphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='levels', to='education.word', verbose_name='Слова на уровне'),
        ),
    ]
