# Generated by Django 5.2.2 on 2025-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_levels_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='words',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
